### ISSUE TITLE
sequoiablocker please 🙏

### ISSUE THREAD

**Issue by huyz** [Theile/sonomablocker#3]

**Comment by Theile** [comment]
I understand the request, but I don't have the time for it these days. 

Besides, I would say the following:

- It's not in our best interests due to security

- it can be delayed with a profile up to 90 days (any software not compatible by then is not worth having)

- it's an old habit from other OS'es to not want to upgrade to the latest and greatest

- today you should be more concerned by not upgrading than by upgrading

I know there can be degrees to how you would write the above, but in the end it is essential to understand that the upgrade is coming. 

That being said, I understand some special situations that could exist, but I don't have the time…

**Comment by huyz** [comment]
Thanks for the reply @Theile .  Totally understand.

I agree that security is more important.  But Apple always breaks stuff whenever I upgrade (because I run so many apps, I'm more susceptible to issues than the average user).
It took them almost a year to fix my Bluetooth issues in Sonoma so that I could use my keyboard.  I'm not looking forward to having more things break.
